// <auto-generated />
using System;
using HotelReservationSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelReservationSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122022227_AddPaymentTransaction")]
    partial class AddPaymentTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotelReservationSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HotelReservationSystem.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PaymentProofImage")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PaymentProofType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProcessedByAdminId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TransactionId");

                    b.HasIndex("ProcessedByAdminId");

                    b.HasIndex("ReservationId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("HotelReservationSystem.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualCheckOut")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CancellationAttempts")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CheckInDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedByUserDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Feedback")
                        .HasColumnType("longtext");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeletedByUser")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastCancellationAttempt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfNights")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("longtext");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RatingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReservationNo")
                        .HasColumnType("longtext");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ReservationId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HotelReservationSystem.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Features")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("int");

                    b.Property<bool>("UnderMaintenance")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            AverageRating = 4.2m,
                            Description = "Cozy single room with basic amenities",
                            IsAvailable = true,
                            MaxGuests = 1,
                            PricePerNight = 1000m,
                            RoomNumber = "101",
                            RoomType = "Single",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 2,
                            AverageRating = 4.2m,
                            Description = "Cozy single room with city view",
                            IsAvailable = true,
                            MaxGuests = 1,
                            PricePerNight = 1000m,
                            RoomNumber = "102",
                            RoomType = "Single",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 3,
                            AverageRating = 4.2m,
                            Description = "Cozy single room with garden view",
                            IsAvailable = true,
                            MaxGuests = 1,
                            PricePerNight = 1000m,
                            RoomNumber = "103",
                            RoomType = "Single",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 4,
                            AverageRating = 4.2m,
                            Description = "Single room with work desk",
                            IsAvailable = true,
                            MaxGuests = 1,
                            PricePerNight = 1000m,
                            RoomNumber = "104",
                            RoomType = "Single",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 5,
                            AverageRating = 4.2m,
                            Description = "Single room with mountain view",
                            IsAvailable = true,
                            MaxGuests = 1,
                            PricePerNight = 1000m,
                            RoomNumber = "105",
                            RoomType = "Single",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 6,
                            AverageRating = 4.2m,
                            Description = "Single room with premium amenities",
                            IsAvailable = true,
                            MaxGuests = 1,
                            PricePerNight = 1000m,
                            RoomNumber = "106",
                            RoomType = "Single",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 7,
                            AverageRating = 4.2m,
                            Description = "Spacious double room with queen bed",
                            IsAvailable = true,
                            MaxGuests = 2,
                            PricePerNight = 2000m,
                            RoomNumber = "201",
                            RoomType = "Double",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 8,
                            AverageRating = 4.2m,
                            Description = "Spacious double room with twin beds",
                            IsAvailable = true,
                            MaxGuests = 2,
                            PricePerNight = 2000m,
                            RoomNumber = "202",
                            RoomType = "Double",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 9,
                            AverageRating = 4.2m,
                            Description = "Spacious double room with balcony",
                            IsAvailable = true,
                            MaxGuests = 2,
                            PricePerNight = 2000m,
                            RoomNumber = "203",
                            RoomType = "Double",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 10,
                            AverageRating = 4.2m,
                            Description = "Double room with city skyline view",
                            IsAvailable = true,
                            MaxGuests = 2,
                            PricePerNight = 2000m,
                            RoomNumber = "204",
                            RoomType = "Double",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 11,
                            AverageRating = 4.2m,
                            Description = "Double room with extra seating area",
                            IsAvailable = true,
                            MaxGuests = 2,
                            PricePerNight = 2000m,
                            RoomNumber = "205",
                            RoomType = "Double",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 12,
                            AverageRating = 4.2m,
                            Description = "Double room with premium bedding",
                            IsAvailable = true,
                            MaxGuests = 2,
                            PricePerNight = 2000m,
                            RoomNumber = "206",
                            RoomType = "Double",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 13,
                            AverageRating = 4.2m,
                            Description = "Luxury suite with living area",
                            IsAvailable = true,
                            MaxGuests = 4,
                            PricePerNight = 3500m,
                            RoomNumber = "301",
                            RoomType = "Suite",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 14,
                            AverageRating = 4.2m,
                            Description = "Luxury suite with jacuzzi",
                            IsAvailable = true,
                            MaxGuests = 4,
                            PricePerNight = 3500m,
                            RoomNumber = "302",
                            RoomType = "Suite",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 15,
                            AverageRating = 4.2m,
                            Description = "Presidential suite with ocean view",
                            IsAvailable = true,
                            MaxGuests = 4,
                            PricePerNight = 3500m,
                            RoomNumber = "303",
                            RoomType = "Suite",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 16,
                            AverageRating = 4.2m,
                            Description = "Executive suite with kitchenette",
                            IsAvailable = true,
                            MaxGuests = 4,
                            PricePerNight = 3500m,
                            RoomNumber = "304",
                            RoomType = "Suite",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 17,
                            AverageRating = 4.2m,
                            Description = "Family suite with separate bedrooms",
                            IsAvailable = true,
                            MaxGuests = 4,
                            PricePerNight = 3500m,
                            RoomNumber = "305",
                            RoomType = "Suite",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        },
                        new
                        {
                            RoomId = 18,
                            AverageRating = 4.2m,
                            Description = "Honeymoon suite with private balcony",
                            IsAvailable = true,
                            MaxGuests = 4,
                            PricePerNight = 3500m,
                            RoomNumber = "306",
                            RoomType = "Suite",
                            TotalRatings = 0,
                            UnderMaintenance = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HotelReservationSystem.Models.PaymentTransaction", b =>
                {
                    b.HasOne("HotelReservationSystem.Models.ApplicationUser", "ProcessedByAdmin")
                        .WithMany()
                        .HasForeignKey("ProcessedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HotelReservationSystem.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedByAdmin");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelReservationSystem.Models.Reservation", b =>
                {
                    b.HasOne("HotelReservationSystem.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId");

                    b.HasOne("HotelReservationSystem.Models.ApplicationUser", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HotelReservationSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HotelReservationSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReservationSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HotelReservationSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelReservationSystem.Models.ApplicationUser", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HotelReservationSystem.Models.Room", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
